version: '3'
services:
  author:
    container_name: aem_author
    build:
      context: ./
      dockerfile: author/Dockerfile
    hostname: 'author'
    ports:
      - '4502:4502'
    volumes:
      - ./logs/author:/opt/aem/crx-quickstart/logs
    depends_on:
      - 'publisher'
  publisher:
    container_name: aem_publisher
    build:
      context: ./
      dockerfile: publisher/Dockerfile
    hostname: 'publisher'
    ports:
      - '4503:4503'
    volumes:
      - ./logs/publisher:/opt/aem/crx-quickstart/logs
  dispatcher:
    container_name: aem_dispatcher
    build:
      context: ./dispatcher
    hostname: 'dispatcher'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./logs/dispatcher:/etc/httpd/logs
    depends_on:
      - 'publisher'
